### ISSUE TITLE
inline webm and gifv

### ISSUE THREAD

**Issue by rlemon** [rlemon/se-chat-dark-theme#10]
do we want this? 

Demo: goto https://gist.github.com/rlemon/3b370467864778f04845 copy and paste it into the console while the chat is open, paste a .gifv or .webm link.

Questions: 

1) Do we want this?
2) should there be a thumbnail the user must click before the video is loaded?
3) should the link be replaced if there is anything else at all in the message content?

**Comment by MadaraUchiha** [comment]
:+1:, but needs a configuration flag to easily cancel. Both because it could get annoying, and because it could be natively implemented sometime in the future.

**Comment by Patsy-issa** [comment]
I like trains

**Comment by rlemon** [comment]
I was thinking of having a thumbnail and onclick load the video (so it is like youtube oneboxes). If the chat ever implements it native I just remove the portion of the extension, I'm not concerned about that bit.

**Comment by rlemon** [comment]
So I went ahead and pushed this to 0.0.1.10 as an experiment to see how it effects users. Please keep all feedback in this issue (of course bugs with the feature can be opened in new issues), 
Thanks.
