### ISSUE TITLE
Optional styles

### ISSUE THREAD

**Issue by rlemon** [rlemon/se-chat-dark-theme#12]
There are some features that are more subjective than others. For these we should probably offer a checkbox option to toggle them on/off 

Example: 
- full width input box.  
- visited links 
- image hover effects

**Comment by Shmiddty** [comment]
This issue should include optional features in javascript like autoplaying gifvs, the color-auto-swatcher, etc

**Comment by rlemon** [comment]
This issue is just a placeholder for the need for optional 'things' in this project.  once the options page is implemented (I'll try for tonight maybe) then we can pop off individual issues for the options. Otherwise I fear this issue will never close and will just keep growing as people think of new options and/or features to add.
