### ISSUE TITLE
Moderator nicknames are too dark

### ISSUE THREAD

**Issue by MadaraUchiha** [rlemon/se-chat-dark-theme#14]
![selection_139](https://cloud.githubusercontent.com/assets/1188951/6939578/ce083604-d876-11e4-9b01-b11c3aa9816f.png)

A better `color` for `.username.moderator` could be somewhere around `#8DB3E5`

**Comment by rlemon** [comment]
seems okay to me, but I'll test out touching it up a bit lighter.
