### ISSUE TITLE
rounded chat messages

### ISSUE THREAD

**Issue by rlemon** [rlemon/se-chat-dark-theme#20]
currently the messages are rounded. I noticed on chat.meta.se they are not (see image below) 

![](http://i.stack.imgur.com/Dz8QX.png)

I personally enjoy the squared messages.. what do we think?

**Comment by Patsy-issa** [comment]
:+1:  for squared.

**Comment by AmaanC** [comment]
Looks better squared!

**Comment by Shmiddty** [comment]
We could make it configurable, or an alternate theme, or remove it. 

I agree that the squared looks better.

**Comment by oliversalzburg** [comment]
Don't mess with my rounded corners!!! Just kidding ;D

**Comment by rlemon** [comment]
I've implemented this but I will add it to the options page to toggle on and off.

**Comment by Unihedro** [comment]
+1 want rounded for MSE chat
