### ISSUE TITLE
I broke user colors and I have no clue how.

### ISSUE THREAD

**Issue by rlemon** [rlemon/se-chat-dark-theme#21]
So a handful of users are not being added to the stylesheet -- and I don't know why. 

They are stored in the chrome.storage (you can prove this by opening the user menu, changing their color, refreshing the page, notice color is retained in the user menu). 

I will continue to investigate this issue further. It would be nice to know if others are seeing the same set of users without the colors. Currently Jan Dvorak, Jason C, Unihedro, Jeremy Banks and a few others that can be found in http://chat.stackoverflow.com/rooms/74583/stack-overflow-2015-moderator-election-chat are broken for me. 

![](http://i.imgur.com/KV1pm61.png)

**Comment by oliversalzburg** [comment]
I'm just going to put this out there. The storage capacity of chrome.storage.sync is limited: https://developer.chrome.com/extensions/storage#property-sync

**Comment by MadaraUchiha** [comment]
I can see Unihedro with a color. What happens if you try clearing your storage?
