### ISSUE TITLE
[Feature] Code editor replacement for input box. 

### ISSUE THREAD

**Issue by Shmiddty** [rlemon/se-chat-dark-theme#23]
1. Add a toggle to enable/disable code editor
2. Posting from code editor mode will prepend text with 4 spaces to trigger code oneboxing. 
3. Can now type code more easily in chat.

...

N. js-fiddle embeddable functionality attached to code blocks?

**Comment by rlemon** [comment]
for now I have implemented a simple system. if you are already in code view and shift + enter you get the last indent. if you have { ending your last line you get a new indent level. if you } in code view you remove an indent level.

**Comment by rlemon** [comment]
that said, I am looking into implementing ACE as a ctrl+k replacement to the standard input.

**Comment by Shmiddty** [comment]
:+1:
