### ISSUE TITLE
gifv and webm support oneboxes too often

### ISSUE THREAD

**Issue by Vogel612** [rlemon/se-chat-dark-theme#30]
Enabling gifv and webm support results in significant additional (unwarranted) oneboxes for such filetypes. Instead of mimicking chat oneboxing behaviour, that only oneboxes when the media is the sole content of the message, inline media also are oneboxed:

![behaviour with gifv / webm support enabled](https://cloud.githubusercontent.com/assets/7288995/9786658/0f818850-57bc-11e5-8d9d-2865d392637a.PNG)

Chat behaviour:

![Chat behaviour: no onebox](https://cloud.githubusercontent.com/assets/7288995/9786642/f1ae29d2-57bb-11e5-9d1f-57344dc64393.PNG)

Currently a workaround is to disable the support, but that's more.. meh

**Comment by rlemon** [comment]
Working on this. version 0.0.4.0 *should* take this update. I've also fractured off the repo and am continuing development on https://github.com/rlemon/se-chat-dark-theme-plus

**Comment by rlemon** [comment]
https://github.com/rlemon/se-chat-dark-theme-plus/commit/6e1a3665e8059ce5158023340eddf2e30433f0ca this is pushed to the webstore now.
